M48
; DRILL file KiCad 10.0.5 date 2026-08-10T02:18:57
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-10T02:18:57+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X175.46Y-127.54
X178.0Y-127.54
X183.46Y-127.54
X186.0Y-127.54
T2
X143.5Y-99.0
X186.5Y-117.2
M30
